Improve enum naming
jeromegn/protobuf.cr pull request #43
Opened 2021-07-18 11:18 UTC by m-o-e

The protobuf guide recommends that enums be upper snakecase.

The buf-linter enforces this and additionally requires that
all enum values be prefixed with the enum name, e.g.:

```protobuf
enum ErrorCode {
  ERROR_CODE_UNSPECIFIED = 0;
  ERROR_CODE_NOT_FOUND = 1;
  ERROR_CODE_ACCESS_DENIED = 2;
  ERROR_CODE_NOT_IMPLEMENTED = 3;
}
```

The reasoning is explained here:
https://docs.buf.build/lint-rules#enum_value_prefix

In the past protobuf.cr would unfortunately translate
this style to rather unpleasant crystal identifiers, e.g.:

```crystal
enum ErrorCode
  ERRORCODEUNSPECIFIED = 0
  ERRORCODENOTFOUND = 1
  ERRORCODEACCESSDENIED = 2
  ERRORCODENOTIMPLEMENTED = 3
end
```

This patch enforces upper snakecase for enums and
strips the prefix when it matches the enum-name.

For the above example it produces:

```crystal
enum ErrorCode
  UNSPECIFIED = 0
  NOT_FOUND = 1
  ACCESS_DENIED = 2
  NOT_IMPLEMENTED = 3
end
```

2021-09-10 18:46 UTC, jgaskins commented
@m-o-e This is great, I was just noticing this myself while working on an OpenTelemetry client last night (I'll try to publish next week). I somehow hadn't noticed this because I don't lint my own `.proto` files but OpenTelemetry apparently does (and, tbh, _should_) so having to write `StatusCode::STATUS_CODE_OK` seemed pretty wonky.

I would love to merge this, but this is a breaking change. Any idea if there's an equivalent of `@[Deprecated]` for enum values?

2021-09-10 18:55 UTC, m-o-e commented
I'm afraid there isn't (at least I don't know of one).

But agree it should be released with a bump of the major version
and ideally upgrade-instructions in the Changelog/README as it
may otherwise not be immediately obvious for upgraders why
enum's broke and how to fix it.

2024-11-02 17:47 UTC, dsisnero commented
Can we get these changes pushed. With the buf ecosystem making grpc easier - it would be nice to use these with crystal

2024-11-02 18:24 UTC, jgaskins commented
Thanks for the reminder about this PR.

Good news is I think we can avoid making this a breaking change. We can have multiple constants with the same value in an `enum`, and when you inspect them they will show up as the first:

```crystal
pp ErrorCode::UNSPECIFIED
# ErrorCode::UNSPECIFIED
pp ErrorCode::ERROR_CODE_UNSPECIFIED
# ErrorCode::UNSPECIFIED

enum ErrorCode
  UNSPECIFIED = 0
  ERROR_CODE_UNSPECIFIED = 0
end
```

2024-11-02 18:26 UTC, jgaskins requested changes

2024-11-21 21:44 UTC, jgaskins approved these changes

2024-11-21 21:44 UTC, merged

2024-11-22 06:06 UTC, jgaskins commented
Released [v2.3.1](https://github.com/jeromegn/protobuf.cr/releases/tag/v2.3.1) with this change